// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnmpsxwzzebjovgwnmee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubXBzeHd6emViam92Z3dubWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDY4NDcsImV4cCI6MjA3MjMyMjg0N30.UbclTFwO17cGYLdOki5Wk7wocixCyK8YvnPZ8OCd2ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});